### ISSUE TITLE
Packet Erro and Lag (Game not Responding)

### ISSUE THREAD

**Issue by walissonsantos** [otland/forgottenserver#1150]
http://oi62.tinypic.com/2rqk6wx.jpg

**Comment by walissonsantos** [comment]
maxPacketsPerSecond = 50

**Comment by walissonsantos** [comment]
Sorry, the bug was caused by excessive items in the mail box ... if you can limit it would be great. The player was with some 70 thousand label in the mail box when the player logava the entire server was with lag.

**Comment by walissonsantos** [comment]
If anyone has interest in resolving this for me I can reward you ... Those interested leave a message.

**Comment by TheSumm** [comment]
There's Bountysource for that.

**Comment by walissonsantos** [comment]
Summ, please contact me on skype: waliss.on@hotmail.com

**Comment by Znote** [comment]
Interesting scenario, aside from the easy solution which is to add a limit to reasonable numbers, perhaps there also are other optimizations we could to related to item storage?

From a technical perspective: 
When you open the mail inbox, do the server load all the items, or just the visible slot ids? Could excessive records in the db be the cause along with mass loading? (Even from cache, loads of unnecessary data would cause a bottleneck)? 

From select query standpoint, perhaps limit 100 (or whatever max visible slots are) could help. 
From table structure, perhaps adding an item_container table could help filter out relevant(visible) items. As a way to load items progressively, instead of loading a huge chunk of data in the start, when your only suppose to be able to view max 100 of them.

**Comment by marksamman** [comment]
The items are loaded to memory when a player logs in, and saved to the database when a player logs out, there's no performance issue with using the inbox while logged in. With a lot of entries in the database, this results in huge INSERT queries. There are many ways to approach this problem, e.g. disabling fsync, max limit for items in inbox, only apply diffs on save, live queries. We will probably end up going with a max limit like there is on the depot chest.

I have barely looked into this issue so I'm not even sure if fsync is the bottleneck here, and even if it is, there are also other ways to work around that than disabling fsync. We could use async queries to insert inbox items and prevent the player from logging in again until all queries have returned success.

**Comment by jo3bingham** [comment]
@marksamman If you add a max limit to the inbox how will you handle house items that get sent to the player's inbox when they sell it that happen to be over the max limit?

**Comment by marksamman** [comment]
@jo3bingham that hasn't been decided, but I would suggest either leaving them in the house or deleting them. We could also count the amount of items and not let the trade go through if it exceeds the free space in the owners inbox. The counting procedure has to be fast though, we could store item count in the House class.

**Comment by jo3bingham** [comment]
@marksamman I ended up solving the issue without imposing an inbox limit by breaking the INSERT query up into several queries instead of one large query when saving items. Also, I added a flag to the players table that gets set/removed before/after the player is saved so that the save function can finish before the player is allowed to login again. I tested with 210k items in my inbox, and log in/out is basically instantaneous.

**Comment by gesior** [comment]
What about 'binary' storage of depots?
Change from relational to binary houses storage made server saves 10-20 times faster.

**Comment by esfomeado** [comment]
I agree with @gesior. This should improve performance although this breaks backwards compatability.

**Comment by ranisalt** [comment]
> only apply diffs on save

Wouldn't SQL `REPLACE` do that for us?

**Comment by degolaot** [comment]
what is the fix??

**Comment by ranisalt** [comment]
@degolaot no, this issue is not trivially to solve.

Apart from `REPLACE`ing queries instead of inserting, we could lazy load items from inbox/depot. Instead of loading the entirety of the item tree, only load the level the player needs to see (but keep in memory). E.g. if the maximum amount of items shown is 30, load only the first 60 and in the background load the rest (or load only if the player removes something).

**Comment by vankk** [comment]
@ranisalt 
Não consegue bolar nenhuma solução para esse problema não?

For who can't read Portuguese:
You can't figure out any fix for this bug?

**Comment by ranisalt** [comment]
No, the only viable solution I see is doing like Tibia: no talkactions for houses.

**Comment by vankk** [comment]
You mean houses in the website? To buy/sell/leave?

**Comment by ranisalt** [comment]
Yes, and the house is only emptied on server save. The problem is when the house is emptied while the server is online, the server has to move manually item by item from the house floor to the player inbox. With absurds like 70k+ items, it means every single item is has to run [this function](https://github.com/otland/forgottenserver/blob/master/src/game.cpp#L1061-L1234).

**Comment by vankk** [comment]
Or maybe to sell/leave could be on server save? .!leavehouse "On the next server save you'll leave this house".

**Comment by ranisalt** [comment]
Yes, that's what I said, only do the move on server save since taking 10sec more on server save is probably better than freezing the server for minutes often.

I don't think there should be an item limit, I myself already sent huge parcels on Tibia, but I think every container should know more information about it's contents (such as it's whole weight and quantity of items) in a way that moving a parcel with 5k+ items is as trivial as moving a single coin.

**Comment by vankk** [comment]
And how we can move it to server save? Any ideas? I could help if I have the necessary knowledge.

**Comment by ranisalt** [comment]
Enqueue every !leavehouse event in a static queue on `House` class and, on server save, start dequeueing and doing dirty job. This is a very simple and probably unoptimized approach.

**Comment by gesior** [comment]
Every house tile is kind of container. Can't we just move these tiles items lists to player inbox items list (so it would execute 'move' only once per tile, not once per item).

I don't understand, how current discussion is related to problem described by thread author. He wrote about problem with 'save'. If we make save of depots binary, it's execution time should be same as save of house.

Async DB queries would be cool, but there can be a big problem with LUA script compability, as there are scripts (bank, maybe others) that load players for temporary use.

**Comment by vankk** [comment]
@gesior 
The problem can happen while sending a parcel or leaving a house with fully items!! 

No one can fix this problem?

**Comment by jo3bingham** [comment]
Has no one read my comment? I solved this 5 months ago.

**Comment by marksamman** [comment]
I've seen your comment, and you're welcome to open a pull request if you believe that your solution is the optimal way to solve this issue.

It's hard to comment on it without knowing the implementation details. I'm not sure why you would need a flag in the player table, you could just mark the player as pending saving in-memory on the server. It also sounds like you're sacrificing atomicity to be able to do that. Does your solution also handle the case of someone sending a parcel/letter to a player while the player is being saved?

**Comment by jo3bingham** [comment]
I don't know why I said I set a table value because I don't do that, but after further testing it seems that breaking the query up in to multiple INSERTs seems to take, on average, the same time as it does to send one bulk INSERT query, as is current. So, I officially retract my previous statements.

**Comment by BenDol** [comment]
This seems like a bit of a critical issue. Is there any attention on this atm?

**Comment by vankk** [comment]
No, seems none gives a fuck.

**Comment by ranisalt** [comment]
> This seems like a bit of a critical issue. Is there any attention on this atm?

Nobody has come up with a good idea yet. This is a pretty complicated issue.

**Comment by djarek** [comment]
At this point we don't really know which point exactly in the saving process takes most time.

**Comment by ranisalt** [comment]
> my guess is that string manipulation when constructing the query is going to be the bottleneck here

Why? Aren't streams speedy enough for string building?

I think @gesior has had a good idea to try, binary storage of inbox items.

**Comment by BenDol** [comment]
What about lazy loading data into memory as its needed? It was already suggested but it woul dbe a good solution. Means only the items that have changed will be saved.

**Comment by GoularPink** [comment]
I have this fix, but I bought this.... If someone is interesting for change cast system for this we can help us!


skype: romildoferreiraa@outlook.com

**Comment by marksamman** [comment]
@GoularPink It is disrespectful of you to ask people who are working to solve this issue for free, to pay you for a solution. Please refrain from commenting if you're not going to contribute to solving this issue.

**Comment by GoularPink** [comment]
I dont need sell or buy, only change, "Behalf" nobody help with cast too. But sorry for my coment then.

**Comment by WibbenZ** [comment]
Djarek has one here?
If there are any bugs im sure someone will fix them, if you send the "fix" to Mark and he approves I will help you get it working and fix the bugs I can(providing I can send them to djarek aswell)
Send me an Mark a pm on OTLand if you wanna do that.

**Comment by WibbenZ** [comment]
You guys can nvm him, doubt he even has the fix.
He wants someone to give him a 1090 cast system and he does not wanna send his fix to mark for approval.
Quote;

"
If you wanna test this, I can show you man, I dont give it for mark... want test? you are in skype?
"

**Comment by GoularPink** [comment]
**If you wanna test this, I can show you man**, I dont give it for mark... **want test?** you are in skype?

:)

**Comment by vankk** [comment]
We have no more news to fix this problem?

**Comment by vankk** [comment]
@jo3bingham 
> I ended up solving the issue without imposing an inbox limit by breaking the INSERT query up into several queries instead of one large query when saving items. Also, I added a flag to the players table that gets set/removed before/after the player is saved so that the save function can finish before the player is allowed to login again. I tested with 210k items in my inbox, and log in/out is basically instantaneous.

Could you share your fix?

**Comment by darkjav** [comment]
@jo3bingham
How you fix?

**Comment by jo3bingham** [comment]
@vankk @darkjav if you read my previous post I explain why my "fix" didn't work

**Comment by gesior** [comment]
1. Anyone tried 'binary' depot storage or asynchronous queries to store items?

2. Anyone checked, if it's lag because of insert query generation (synchronous, in engine) or database (MySQL, can be called asynchronous with extra column in table players: 'is_saving')?

**Comment by marksamman** [comment]
Unfortunately, most people who are affected by this issue are only asking for a fix and have yet to provide any profiling data, so we don't know where the bottleneck is.

**Comment by vankk** [comment]
@marksamman 
What do you mean with?
> any profiling data

**Comment by marksamman** [comment]
I don't mean anything more specific, any profiling data may turn out to be useful, a call graph would be nice. There are many different tools you can use, such as perf record or gprof.

**Comment by gesior** [comment]
@marksamman 
I did some test with otserv 0.6.3.
I added binary save to player items and compares times of binary and normal save.


**23.587 ITEMS:**

Generate query rows [stringstream] 26/27/25 ms
Change query rows to SQL query [string] 1/0/1 ms
Execute query [query length: 726.117 letters , rows: 23.587] 151/168/229 ms

TOTAL TIME NORMAL SAVE: **176 - 257 ms**

Generate binary data [PropWriteStream] 7/8/7 ms
Change binary data to SQL query [string] 2/2/2 ms
Execute query [query length: 829.425 letters , rows: 1] 5/6/6 ms

TOTAL TIME BINARY SAVE: **14 - 16 ms**

**40.004 ITEMS:**

Generate query rows [stringstream] 48/43/44 ms
Change query rows to SQL query [string] 0/0/1 ms
Execute query [query length: 1.262.381 letters , rows: 40,004] 437/360/365 ms
TOTAL TIME NORMAL SAVE: **404 - 486 ms**

Generate binary data [PropWriteStream] 15/15/14 ms
Change binary data to SQL query [string] 3/3/3 ms
Execute query [query length: 1.387.191 letters , rows: 1] 10/10/12 ms
TOTAL TIME BINARY SAVE: **27 - 30 ms**

**Other problem..**

Time to add 2000 new items to player (like: hi 2000 mana fluid yes):
120 items on player (empty backpacks): 0.8 second
25.0000 items on player: 20 seconds!

**Comment by ranisalt** [comment]
Can someone actually provide a database with enough data to cause freezing?

Just dump your DB and clear player names, account names and passwords and gzip.

**Comment by gesior** [comment]
Did anyone try to make it work like on real tibia? Load items from database at start of server and save them all at shutdown?
I'm not sure what problems may occur, if you keep items in memory when player logout [items duration etc.].

**Comment by wgrriffel** [comment]
@gesior whats for sure will occur is people using bots to create characters and just get logged in, load to memory their initial items, log out, and on and on and on, overloads the memory and crash it anyway.

**Comment by gesior** [comment]
Items of 25k players [tibia 8.0, not stackable runes] in database uses 200MB, even if it uses 2GB RAM [depends on 'item' struct in distro].. who cares? Most of dedics got 16+ GB RAM.

Server load items of player at start or when there login player which items are not cached in RAM yet. Someone create new char, get around 10 items, login.. server items cache uses extra 1-5 KB RAM, it would take days to crash server with 8GB RAM. Admin can check in database number of characters and their levels and remove players that does not play.

**Comment by ranisalt** [comment]
The biggest memory hog is currently the map IIRC. Items are simple and reutilize a lot of memory.

**Comment by wgrriffel** [comment]
@gesior most of servers are running at vps, dedicated is most expensive for servers that haven't that much to pay, and the bot problem is it's a bot, it don't care how much ram you have, if you search on youtube, some guys login more than hundred bots only for abuse of lower level quests, so the problem is we dealing with infinite, your both propose are a better choice than already is, but problem can be explored yet,and a lot of code for it, so the best way imo is limiting items transfer to mailbox/depot, tibia have it why don't?

**Comment by gesior** [comment]
@wgrriffel 
On real tibia you put parcel on mailbox and it does not go to depot, if there is too many items inside your depot?
It looks like super easy to abuse, spam someones depot with parcels and he cant send lootbag :(

**Comment by wgrriffel** [comment]
@gesior there is a limit but it is large, and after it's full seens like server doesn't read that items that are on a queue, it's added after you empty a slot, i feel like that, and the same occurs to tiles.

**Comment by Healek** [comment]
@ranisalt @gesior @marksamman 
this problem has been solved in master branch? thank u.

**Comment by ranisalt** [comment]
I just took a look at this issue and I found a lot of the time is spent on `Game::internalMoveItem` as I pointed above. Changing some `std::list`s to `std::vector`s improved the time to move the items by a few % (I'd guess about 20%) but still does not fix the issue.

**Comment by gesior** [comment]
@wgrriffel 
It can be a solution. Keep mailbox in other table (I think it's already in TFS 1.x) and load only first X items from that container. To load more items player must relog... it's not a problem for normal players, because they don't get 1000 parcels.

There is still problem with super big parcels. It would require a lot of source changes to make containers parse dynamically (we could load from database items, but we don't want to generate 'Item' instances in engine).

Obvious fix for that problem would be loading all items from database at start of server (it's 2017!, who cares about extra 1-2GB RAM on 1000+ online server) and then just get pointer to containers that are placed in RAM (not on map/players) - player loading time would be 0.001 sec, no matter how many items they have.
We would not remove them from RAM when player logout, just set player items to some 'state' and other 'thread' (with second connection to database) would store them in database without any lag in game.
I'm pretty sure that's how it works on tibia.com (except 'save' thing that occurs only once a day).

**Comment by wgrriffel** [comment]
@gesior kind of agree, but at some time it has to save, and probably would end up in same issue.

**Comment by gesior** [comment]
@wgrriffel 
1. Save items of players when they are offline - we can do it in some new 'thread', not in main OTS thread which freez server for save time.
2. 'Lock' (block login to character) of players which items are in state 'saving' (other 'thread' uses that items, we can't let 'main' thread modify items while save)

If we need to save server with players online, we could make fast (not really with milion items in depot, but muuch faster then current saves) copy of 'Item' objects in C++ and then save it to database in other thread.

Of course these changes would require a lot of programming, but it's only way to fix that lag on login/logout - NOT LOAD ITEMS ON LOGIN/LOGOUT!

**Comment by UltraMC** [comment]
How much freedom do I have to fix that? From bug reports it seems that's an issue with volume of SQL requests and for that there's a lot of solutions.

@jo3bingham approach is OK'ish, but instead of breaking one query to multiple I want to go with optimizing big one. Is change to database schema is an option?

First step is going to be creation a reproducable case...

**Comment by djarek** [comment]
@UltraMC 
If the changes are small then it's acceptable. Otherwise you would need to wait for 2.0 (most likely 1.3 will be the last version in the 1.x series of tfs).

**Comment by ranisalt** [comment]
Being generic, if you don't change the server behavior, go on. We still have time before 1.3 to accept breaking code.

**Comment by UltraMC** [comment]
@djarek @ranisalt What's about "breaking changes" in "2.0"?

If I introduce any is it ok if I'll provide automatic hads-free migration tools (will slow down startup of a server, or run over demand)

**Comment by djarek** [comment]
By breaking changes we mean anything that would need a nontrivial rewrite of stuff in the data pack. Migrations are ok, as long as they don't significantly break other related tools like Znote's webapp.

**Comment by OPfeajoief13** [comment]
bounty increased

**Comment by gesior** [comment]
Bounty increased by 10$
I want to see some awesome code that fix it!

**Comment by Xagul** [comment]
I think at the end of the day, no matter what route you take to "optimize" this area of the server, players can always just throw more items at the problem.

An example:
Lets say you have a player with 100,000 items in their depot and it causes the server to lag for 10 seconds.
We find the magical solution to optimize the code so that those 100k items are saved in 0.1 second.
This is fantastic! But the player can just throw 1 billion items into the depot to lag the server again.
There also comes a point where the sheer number of items they require to cause lag eats up memory and disk space on the server. I know this seems like an unlikely scenario but the fact of the matter is that it is possible.

In my opinion the best and only way to truly solve this issue is to limit the amount of items a player can have in their house, in their depot, in their mailbox, and on their person. These values could be changed in the config.xml by people as they see fit.

- **Max depot items:** We already have this
- **Max player items:** We basically already have this via capacity
- **Max house items:** I saw a reply above about saving the total items in the house in the house class, this is a perfect idea as we can then make a function to easily access the house item count in lua.
- **Max inbox items:** There are a couple issues this could present but I think they are (in concept) very easy to solve.
**A)** When a player tries to mail something it will check the destination inbox capacity, If it's full, the mail will not send and will alert the player about it being full. To prevent bombing another players inbox so they cannot parcel loot, maybe add a second limit to the inbox for people parceling to others (say 1k items is the limit, make it so if you aren't the owner of the inbox, the limit is 500). This would allow a buffer for the owner to use if needed.
**B)** When a player tries to leave their house, compare the number of items inside of the house to the inbox capacity. If there isn't enough room, the house will remain owned by the player and alert them that their inbox doesn't have enough room. 

P.S.
The item count for the house/inbox should probably be stored in the database somewhere as well so websites also have access to it for their functions.


I want to be very clear here... I am not saying the code shouldn't be optimized. Of course, if possible, any optimization should be done. I'm simply saying it doesn't fix the issue at hand here.

**Comment by ranisalt** [comment]
> We find the magical solution to optimize the code so that those 100k items are saved in 0.1 second.
> This is fantastic! But the player can just throw 1 billion items into the depot to lag the server again.

Then we should find a solution with lower complexity, instead of just writing faster code for the same algorithm.

**Comment by TwistedScorpio** [comment]
Basically CIP's way.

Load players into memory.
Unload players into a swap file after some time without logging in.
If player attempts to login and swap file exists, load the player info from this file.

**Comment by K3V1N-BR** [comment]
Hello @ranisalt, some time ago you asked for a database with enough data to cause the freezing, I was making some tests here to try solve this issue but nothing so far, if you want I can share the database and the test environment with you, this issue is very critical if someone wants damage a server.

**Comment by DSpeichert** [comment]
@K3V1N-BR Try attaching the DB dump here.

**Comment by Znote** [comment]
I think there are several approaches to deal with this, which may fit different server setups. I think the best way would be to support multiple solutions through config.lua:

Playerloading memmory overhead:
* **Minimal** - Classic way, players are loaded into memmory on login, and loaded out in logout.
* **Minimal Optimist** - Classic way, but loads player out of memmory 1 hour/xx minutes after logout (immediate shutdown/closeserver/server save). Prevents relog lag spam, but may cause one freeze per big player after the timeout.
* **Active** - Loaded into memmory on login, loaded out on shutdown.
* **PreActive** - Players who has logged in past xx days are loaded in memmory on startup. Loaded out on shutdown.
* **Full** - All players are loaded into memmory on startup, loaded out on shutdown.

With the big overhead (active) options, it might be a good idea to also add a "unload on upper RAM size cap". So if tfs.exe exceeds XXGB memmory, trigger a Lua globalevent and unload the inactive players from memmory to save up RAM. 

That way, you can make do with a small box, but if you got 16+GB ram, you can just go all ham on it.

**Comment by Kamenuvol** [comment]
indexing the table by player is worth?

**Comment by Gagoosh** [comment]
The saving inbox items on shutdown/server save idea is good, but while I was testing it, mysql server went down due to the amount of items being inserted (probably because of the time it took the query to be executed), thus the problem is not only the freezes it can cause when server is online, but also crashing in the middle of the query and not saving the items.
Spliting the query into smaller ones would probably fix that.

**Comment by CristoferMartins** [comment]
My simple idea is just move the player loading/saving to a helper thread since the most expensive operation related to dabase is player loading/saving.

**Comment by marcelobcortes** [comment]
extending ZNote's
**Semi Full / Semi PreActive**
find heavy players and load them all on startup

**Comment by CristoferMartins** [comment]
Its all depends of how much memory it will be spent.

**Comment by CristoferMartins** [comment]
I also want to add that in the player save mode we can add all the queries as a  list of strings and then in another thread we call execute all the queries in one transaction.

**Comment by Kamenuvol** [comment]
is the option 'load by container' possible? exceeded container when leaving houses could load only its "normal size" (only shown items) and loading 1 by 1 when removing others

**Comment by Gagoosh** [comment]
@Kamenuvol Idk how that would be done, everytime he removes an item from the container we access the database to get the next item to be shown? Thats no viable

If everytime he removes an item we get the next item from memory, well then... it is already in memory.

**Comment by Ochmar** [comment]
If the resolution is applicable on [OTHire ](https://github.com/TwistedScorpio/OTHire) source also, I'll put additional +10$ for a bounty.

**Comment by Ochmar** [comment]
Forget my previous +10$. I'm giving +50$ if the solution works for OTHire (does not have to be 1:1 code, but logic is enough).

**Comment by JSkalskiSBG** [comment]
I can only add one information from my tests about saving without lag:
You can 'fork' process of RL map with 4GB RAM in 30 ms on linux.

I did not expect it can be that fast. Then I read that Apache/PHP forks a lot and clever people worked for years to make it work super fast on new linux kernels.

It creates second process with same memory (not copy of memory, so MEMORY USE DOES NOT GROW). Just set all process RAM to 'read only' mode. So if any thread (game or save) tries to modify some value, it's moved to other address and saved there. Second process got no idea about it. During 'save' write to RAM operations are around 30% slower. After you do save in second process, you can exit that process and write operations to RAM go back to full speed.

So it's possible to create not lagging save of all players (ALL players, in case when we load all players items at start) and houses. It forks super fast and does not use 2x more RAM.

**Comment by Ochmar** [comment]
Hmm, it seems tricky.
Do you have any tests results you can share and/or are you willing to share/sell the code itself?

And is it you @gesior @JSkalskiSBG or is it low effort impersonate?

**Comment by gesior** [comment]
@Ochmar 
It's account I use when I'm at work.

I'm working on solution for kasteria.pl. Problem there is much bigger, because there is no stackable potions/runes and after 4 weeks there are 5 milions items in database and some players got over 30k items depot. I got limits of containers/items in sources. I set it to max. 100k items per player, but I would like to make it unlimited and not lagging.

I should finish all scripts and tests in 1-2 months. Then I will think about releasing it for this 55$ bounty.

**Comment by Ochmar** [comment]
@gesior Okay, thanks for dispelling doubts.

If people withdraw from the bounty, I can cover it all myself - just hit me up.
Thanks for your contribution!

**Comment by djarek** [comment]
@gesior fork and threads don't mix very well... Note that `fork` only clones the 1 thread that called `fork` and all the other data structures, including mutexes (sic), may be in an unusable state.

**Comment by gesior** [comment]
@djarek 
That's why I call fork from dispatcher thread (exactly from LUA function) and use new DB connection to save everything. All this process does is reading map/players, no mutexes/resources from game process involved.
While executing LUA function in dispatcher, all mutexes and resources needed for map/player manipulation must be blocked.

Anyway, first thing I will test is binary save/load of items. Then I will test, if it speed up, if I cache binary items data in some vector in C++.

Then I will test forking dispatcher process and saving all players and house items to file - in case of crash you can load saved players/items/houses by executing file in mysql.

So my final result will be:
1. Load all items at start.
2. Save players items and houses to file every few minutes - in forked process = no lag.
3. Save players items and houses at shutdown of server.

In case of server crash, database goes back to last server start state - like on real tibia, but I can load changes made during day from file.

**Comment by JSkalskiSBG** [comment]
@djarek 
Can you point some possible reasons of crash/bug in my solution from post above? I'm not good in mutexes and I don't want to crash my server by fast-save feature.

Results from binary save/load of depot tests:
```
25k items:

NORMAL
load: 27 ms
save: 162 ms
BINARY:
load: 10 ms
save: 10 ms

50k items:

NORMAL
load: 61 ms
save: 267 ms
BINARY:
load: 21 ms
save: 19 ms

100k items:

NORMAL
load: 116 ms
save: 677 ms
BINARY:
load: 53 ms
save: 72 ms
```

**Comment by guianm** [comment]
I think I've found an article with some points that @djarek mentioned.
http://www.linuxprogrammingblog.com/threads-and-fork-think-twice-before-using-them

**Comment by djarek** [comment]
@gesior IIRC the only library functions you're allowed to call in the child process after `fork` (in a multithreaded application) are those that are signal-safe. You can't even allocate (or deallocate memory).

**Comment by gesior** [comment]
57 months and no solution? Gesior's time! :)

I saw one guys offer 'Items saving/loading on other thread [500$]', but I think it should be open source.

### My current conception (60% of code is ready and tested on 1.3)

**Player items cache** - load player items once per server restart, save them in asynchronous thread.
**Player items binary format in database** - save and load player items up to 10 times faster.

**Items** = all player items: 'on player', depots and inbox.

1. Keep items copies in RAM in objects PlayerCacheData*. **[DONE]**
2. On player load, check, if there are items in cache for given GUID. If there are, copy them into Player*. If not, load from database and put copy in PlayerCacheData*. **[DONE]**
3. On player save, copy Player* items into PlayerCacheData*. Add given PlayerCacheData* to 'items to save queue'. **[DONE]**
4. New thread (added to TFS) will save items from PlayerCacheData* to database. Class similar to DatabaseTasks, running on own DB connection. **[DONE]**
5. Add option to save items in database in binary format. [Tested on Kasteria.pl, not implemented for TFS 1.3 yet]
6. Add LUA functions to manipulate cache:
- possibility to load all players items in 'onStartup' event
- possibility to load all players items to cache, change config.lua to make it use 'binary save' and save all cache to database = change database from relational to binary on running server


Coping items over and over could be removed...
...but then it would be not possible to save player until server restart. OTSes are not stable enough for 1 save per 24 hours, so I did implement what I described above.

When I finish all 6 points I will run benchmark to check if it's faster to clone items structure **or** to serialized/deserialize them to binary format.

**Comment by ranisalt** [comment]
> save them in asynchronous thread

Don't forget that players might log in before being saved, take care not to create inconsistencies.

**Comment by gesior** [comment]
@ranisalt 
Player cache data read/write is in mutex.
Cloning player items to/from cache is synchronous and is in dispatcher thread - called from iologindata.
Extra thread clones items from 'cache' to 'cache copy' in mutex. Unlock mutex and then serialize data for database and send query.

In current implementation are 2 mutexes. First is for 'cache map' (player ID -> items), that blocks possibility to operate on map by 2 threads. Second mutex is in each 'player cache' instance (items) that block possiblity to read/write in same time by 2 threads.

When I will finish first version, I will publish it and then we will have a looot of time to talk about mutexes, items consistence and all things that sucks in multithread programming :smile:

**Comment by ranisalt** [comment]
> Player cache data read/write is in mutex.

Then again a player will be blocked from logging in if he is being stored?

**Comment by gesior** [comment]
Yes. Normal TFS (whole server) is blocked for time of generating query and storing it in database - saving player.
After my changes it's only blocked for time of cloning all items in RAM. It's around 20 times faster. Generating query and storing it in database is in other thread and is not blocking login/logout.

After changes maximum 'block time' when you do fast-relog will be 3x clone all items (1. clone from player to cache, 2. clone cache to database thread, 3. clone from cache to player).
Normal TFS would block for time of generating save query, storing save query, loading items from database and parsing them into 'items structure'.
In case of 100k items it should reduce lag from 800ms to 50ms.

**Comment by gesior** [comment]
**First benchmark of new code with 168k items in backpack**
Cache player items (on logout): 31-36ms
Load player items from cache (on login): 26 - 29ms
Save items cache to database (**asynchronous**): 4200ms

**Old code:**
Save player items to database (on logout): 3000ms
Load player items from database (on login): 450-560ms

I run database with default XAMPP settings, so it's slow, but even with super-optimized MySQL it would take around 1000ms to save player with 168k items.

**Comment by Ochmar** [comment]
Hello @gesior 
How much does it increase your RAM usage? Like 10%? 50%?

**Comment by gesior** [comment]
@Ochmar 
I don't know. Maybe some C++ expert could calculate how much RAM uses 1 item, but I can't.
I assume it's less than 1KB per item. If you got 1 year old server with 1000 online you may have around 1 million items in depots, inboxes and on players. Million KB  = 1 GB RAM.

In most cases. you have more items in houses. than on players and house items are all loaded to RAM at start. Even, if you decide to 'load all players items cache' at server startup, it should not be a problem with common dedic (8+ GB RAM).

// There were some discussion in some Issue about 'Item' size in RAM and as I remember they were talking about values like 82 bytes, not 1KB.

**Comment by gesior** [comment]
If anyone is interested in testing I released first version of clean code.
It's not tested yet. I will test it when I get back home.

All changes:
https://github.com/otland/forgottenserver/compare/master...gesior:issue_1150

**Comment by gesior** [comment]
If anyone is interested in test or fixing memory leaks (which are there probably):
https://github.com/gesior/forgottenserver/commit/14bb1a66ec39735157d8b9e214418b8c4df65864

Updated version of binary items save, ~40% faster.

**Comment by gesior** [comment]
About test of this code:
askara.net starts on monday. I added there binary save of player items/depots, items RAM cache and delayed save of items (2 seconds threshold).
There should be 500+ on start and we will see how smooth will be game with load/save times below 1ms.

**Comment by Jcalcaldev** [comment]
@gesior How did that go?

**Comment by gesior** [comment]
> @gesior How did that go?

Failed :(
Askara database connection code is partially from 8 years old OTServ. Sending big amounts of binary data makes random database connection drops. I tested it on TFS with big amount of data and it did not drop connection to DB.
I had to go back to relational save on Askara.

I'm not working on Askara anymore, but if I would, I would add saving binary data to files on HDD (like old XML servers did), not to database. Databases (mysql, postgresql, probably all!) have no optimization for handling binary data - it cannot be cached in RAM! DELETE/UPDATE/INSERT result in instant write to HDD - they work super slow :(

**Comment by ranisalt** [comment]
You can try combining memory map with a contiguous data structure to handle that graciously, letting the operating system flush to disk when idle.

**Comment by DSpeichert** [comment]
@ranisalt 
Basically, [FlatBuffers](https://google.github.io/flatbuffers/) or [Cap'n'proto](https://capnproto.org/)
