### ISSUE TITLE
Error C2131 while compiling

### ISSUE THREAD

**Issue by adrianozc** [otland/forgottenserver#2006]
Hello, while trying to compile I had an error show up

1>------ Build started: Project: theforgottenserver, Configuration: Release x64 ------
1>  items.cpp
1>..\src\items.cpp(60): error C2131: expression did not evaluate to a constant
1>  ..\src\items.cpp(60): note: failure was caused by returning the address of or a reference to a temporary
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

I did not edit the coding at all, I downloaded the files just as they are in here: https://github.com/otland/forgottenserver/wiki/Compiling-on-Windows

I am using MVSC 2015, using latest version of TFS (1.2) and TFS SDK 3.2 libraries, what could be the solution to this error?

The error is caused in this line of code:

constexpr auto OTBI = OTB::Identifier{ { 'O','T', 'B', 'I' } };

**Comment by marksamman** [comment]
A simple fix would be to remove constexpr from that line, you're not going to notice any difference anyway. Unless there's a way to make MSVC evaluate it as a constant expression, that's how it will be fixed. Leaving this open for now.

**Comment by adrianozc** [comment]
Confirmed, thanks.

**Comment by wgrriffel** [comment]
master branch are compiling just fine with MSVC for me.

**Comment by marksamman** [comment]
Does this happen to anyone else? Is it possible that this was fixed in a VS update and that @adrianozc isn't running the latest version?

**Comment by wgrriffel** [comment]
btw my MSVC version that i've compiled, update 3 june 27, 2016

**Comment by Fluppix** [comment]
I just downloaded the latest sources and tried to compile for win 10, 64 bits. It gave me the same error, the fix you mentioned above works @marksamman

**Comment by ranisalt** [comment]
It's 2017 and MSVC still doesn't properly implement constexpr that date back to 2009. Shame on you, Microsoft.

**Comment by conde2** [comment]
Same problem here

Severity	Code	Description	Project	File	Line
Error	C2131	expression did not evaluate to a constant	theforgottenserver	C:\Users\joao\Desktop\forgottenserver-master\src\items.cpp	60

**Comment by kornholi** [comment]
You need MSVC 2015 Update 3.
